!STARTOFREGISTRYGENERATEDFILE 'ExtPtfmLoads_Types.f90'
!
! WARNING This file is generated automatically by the FAST registry.
! Do not edit.  Your changes to this file will be lost.
!
! FAST Registry
!*********************************************************************************************************************************
! ExtPtfmLoads_Types
!.................................................................................................................................
! This file is part of ExtPtfmLoads.
!
! Copyright (C) 2012-2016 National Renewable Energy Laboratory
!
! Licensed under the Apache License, Version 2.0 (the "License");
! you may not use this file except in compliance with the License.
! You may obtain a copy of the License at
!
!     http://www.apache.org/licenses/LICENSE-2.0
!
! Unless required by applicable law or agreed to in writing, software
! distributed under the License is distributed on an "AS IS" BASIS,
! WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
! See the License for the specific language governing permissions and
! limitations under the License.
!
!
! W A R N I N G : This file was automatically generated from the FAST registry.  Changes made to this file may be lost.
!
!*********************************************************************************************************************************
!> This module contains the user-defined types needed in ExtPtfmLoads. It also contains copy, destroy, pack, and
!! unpack routines associated with each defined data type. This code is automatically generated by the FAST Registry.
MODULE ExtPtfmLoads_Types
!---------------------------------------------------------------------------------------------------------------------------------
USE ExtPtfmLoadsDX_Types
USE NWTC_Library
IMPLICIT NONE
! =========  ExtPtfmLd_InitInputType  =======
  TYPE, PUBLIC :: ExtPtfmLd_InitInputType
    INTEGER(IntKi) , DIMENSION(1:3)  :: PtfmPos = 0_IntKi      !< Position of the platform [-]
    INTEGER(IntKi) , DIMENSION(1:3,1:3)  :: PtfmOrient = 0_IntKi      !< Orientation of the platform [-]
    REAL(ReKi)  :: PtfmRefzt = 0.0_ReKi      !< Vertical distance from the ground level [onshore], MSL [offshore wind or floating MHK], or seabed [fixed MHK] to the platform reference point [meters]
  END TYPE ExtPtfmLd_InitInputType
! =======================
! =========  ExtPtfmLd_InitOutputType  =======
  TYPE, PUBLIC :: ExtPtfmLd_InitOutputType
    CHARACTER(ChanLen) , DIMENSION(:), ALLOCATABLE  :: WriteOutputHdr      !< Names of the output-to-file channels [-]
    CHARACTER(ChanLen) , DIMENSION(:), ALLOCATABLE  :: WriteOutputUnt      !< Units of the output-to-file channels [-]
    TYPE(ProgDesc)  :: Ver      !< This module's name, version, and date [-]
    REAL(ReKi)  :: AirDens = 0.0_ReKi      !< Air density [kg/m^3]
  END TYPE ExtPtfmLd_InitOutputType
! =======================
! =========  ExtPtfmLd_ContinuousStateType  =======
  TYPE, PUBLIC :: ExtPtfmLd_ContinuousStateType
    REAL(ReKi)  :: blah = 0.0_ReKi      !< Something [-]
  END TYPE ExtPtfmLd_ContinuousStateType
! =======================
! =========  ExtPtfmLd_DiscreteStateType  =======
  TYPE, PUBLIC :: ExtPtfmLd_DiscreteStateType
    REAL(ReKi)  :: blah = 0.0_ReKi      !< Something [-]
  END TYPE ExtPtfmLd_DiscreteStateType
! =======================
! =========  ExtPtfmLd_MiscVarType  =======
  TYPE, PUBLIC :: ExtPtfmLd_MiscVarType
    REAL(ReKi)  :: phi_cfd = 0.0_ReKi      !< Blending ratio of load from external driver [0-1] [-]
  END TYPE ExtPtfmLd_MiscVarType
! =======================
! =========  ExtPtfmLd_ConstraintStateType  =======
  TYPE, PUBLIC :: ExtPtfmLd_ConstraintStateType
    REAL(ReKi)  :: blah = 0.0_ReKi      !< Something [-]
  END TYPE ExtPtfmLd_ConstraintStateType
! =======================
! =========  ExtPtfmLd_OtherStateType  =======
  TYPE, PUBLIC :: ExtPtfmLd_OtherStateType
    REAL(ReKi)  :: blah = 0.0_ReKi      !< Something [-]
  END TYPE ExtPtfmLd_OtherStateType
! =======================
! =========  ExtPtfmLd_ParameterType  =======
  TYPE, PUBLIC :: ExtPtfmLd_ParameterType
    TYPE(ExtPtfmLdDX_ParameterType)  :: DX_p      !< Data to send to external driver [-]
  END TYPE ExtPtfmLd_ParameterType
! =======================
! =========  ExtPtfmLd_InputType  =======
  TYPE, PUBLIC :: ExtPtfmLd_InputType
    TYPE(ExtPtfmLdDX_InputType)  :: DX_u      !< Data to send to external driver [-]
    TYPE(MeshType)  :: PtfmMotion      !< motion on the platform [-]
  END TYPE ExtPtfmLd_InputType
! =======================
! =========  ExtPtfmLd_OutputType  =======
  TYPE, PUBLIC :: ExtPtfmLd_OutputType
    TYPE(ExtPtfmLdDX_OutputType)  :: DX_y      !< Data to get from external driver [-]
    TYPE(MeshType)  :: PtfmMesh      !< Loads at the platform reference point [-]
  END TYPE ExtPtfmLd_OutputType
! =======================
CONTAINS

subroutine ExtPtfmLd_CopyInitInput(SrcInitInputData, DstInitInputData, CtrlCode, ErrStat, ErrMsg)
   type(ExtPtfmLd_InitInputType), intent(in) :: SrcInitInputData
   type(ExtPtfmLd_InitInputType), intent(inout) :: DstInitInputData
   integer(IntKi),  intent(in   ) :: CtrlCode
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_CopyInitInput'
   ErrStat = ErrID_None
   ErrMsg  = ''
   DstInitInputData%PtfmPos = SrcInitInputData%PtfmPos
   DstInitInputData%PtfmOrient = SrcInitInputData%PtfmOrient
   DstInitInputData%PtfmRefzt = SrcInitInputData%PtfmRefzt
end subroutine

subroutine ExtPtfmLd_DestroyInitInput(InitInputData, ErrStat, ErrMsg)
   type(ExtPtfmLd_InitInputType), intent(inout) :: InitInputData
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_DestroyInitInput'
   ErrStat = ErrID_None
   ErrMsg  = ''
end subroutine

subroutine ExtPtfmLd_PackInitInput(RF, Indata)
   type(RegFile), intent(inout) :: RF
   type(ExtPtfmLd_InitInputType), intent(in) :: InData
   character(*), parameter         :: RoutineName = 'ExtPtfmLd_PackInitInput'
   if (RF%ErrStat >= AbortErrLev) return
   call RegPack(RF, InData%PtfmPos)
   call RegPack(RF, InData%PtfmOrient)
   call RegPack(RF, InData%PtfmRefzt)
   if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLd_UnPackInitInput(RF, OutData)
   type(RegFile), intent(inout)    :: RF
   type(ExtPtfmLd_InitInputType), intent(inout) :: OutData
   character(*), parameter            :: RoutineName = 'ExtPtfmLd_UnPackInitInput'
   if (RF%ErrStat /= ErrID_None) return
   call RegUnpack(RF, OutData%PtfmPos); if (RegCheckErr(RF, RoutineName)) return
   call RegUnpack(RF, OutData%PtfmOrient); if (RegCheckErr(RF, RoutineName)) return
   call RegUnpack(RF, OutData%PtfmRefzt); if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLd_CopyInitOutput(SrcInitOutputData, DstInitOutputData, CtrlCode, ErrStat, ErrMsg)
   type(ExtPtfmLd_InitOutputType), intent(in) :: SrcInitOutputData
   type(ExtPtfmLd_InitOutputType), intent(inout) :: DstInitOutputData
   integer(IntKi),  intent(in   ) :: CtrlCode
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   integer(B4Ki)                  :: LB(1), UB(1)
   integer(IntKi)                 :: ErrStat2
   character(ErrMsgLen)           :: ErrMsg2
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_CopyInitOutput'
   ErrStat = ErrID_None
   ErrMsg  = ''
   if (allocated(SrcInitOutputData%WriteOutputHdr)) then
      LB(1:1) = lbound(SrcInitOutputData%WriteOutputHdr)
      UB(1:1) = ubound(SrcInitOutputData%WriteOutputHdr)
      if (.not. allocated(DstInitOutputData%WriteOutputHdr)) then
         allocate(DstInitOutputData%WriteOutputHdr(LB(1):UB(1)), stat=ErrStat2)
         if (ErrStat2 /= 0) then
            call SetErrStat(ErrID_Fatal, 'Error allocating DstInitOutputData%WriteOutputHdr.', ErrStat, ErrMsg, RoutineName)
            return
         end if
      end if
      DstInitOutputData%WriteOutputHdr = SrcInitOutputData%WriteOutputHdr
   end if
   if (allocated(SrcInitOutputData%WriteOutputUnt)) then
      LB(1:1) = lbound(SrcInitOutputData%WriteOutputUnt)
      UB(1:1) = ubound(SrcInitOutputData%WriteOutputUnt)
      if (.not. allocated(DstInitOutputData%WriteOutputUnt)) then
         allocate(DstInitOutputData%WriteOutputUnt(LB(1):UB(1)), stat=ErrStat2)
         if (ErrStat2 /= 0) then
            call SetErrStat(ErrID_Fatal, 'Error allocating DstInitOutputData%WriteOutputUnt.', ErrStat, ErrMsg, RoutineName)
            return
         end if
      end if
      DstInitOutputData%WriteOutputUnt = SrcInitOutputData%WriteOutputUnt
   end if
   call NWTC_Library_CopyProgDesc(SrcInitOutputData%Ver, DstInitOutputData%Ver, CtrlCode, ErrStat2, ErrMsg2)
   call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   if (ErrStat >= AbortErrLev) return
   DstInitOutputData%AirDens = SrcInitOutputData%AirDens
end subroutine

subroutine ExtPtfmLd_DestroyInitOutput(InitOutputData, ErrStat, ErrMsg)
   type(ExtPtfmLd_InitOutputType), intent(inout) :: InitOutputData
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   integer(IntKi)                 :: ErrStat2
   character(ErrMsgLen)           :: ErrMsg2
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_DestroyInitOutput'
   ErrStat = ErrID_None
   ErrMsg  = ''
   if (allocated(InitOutputData%WriteOutputHdr)) then
      deallocate(InitOutputData%WriteOutputHdr)
   end if
   if (allocated(InitOutputData%WriteOutputUnt)) then
      deallocate(InitOutputData%WriteOutputUnt)
   end if
   call NWTC_Library_DestroyProgDesc(InitOutputData%Ver, ErrStat2, ErrMsg2)
   call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
end subroutine

subroutine ExtPtfmLd_PackInitOutput(RF, Indata)
   type(RegFile), intent(inout) :: RF
   type(ExtPtfmLd_InitOutputType), intent(in) :: InData
   character(*), parameter         :: RoutineName = 'ExtPtfmLd_PackInitOutput'
   if (RF%ErrStat >= AbortErrLev) return
   call RegPackAlloc(RF, InData%WriteOutputHdr)
   call RegPackAlloc(RF, InData%WriteOutputUnt)
   call NWTC_Library_PackProgDesc(RF, InData%Ver) 
   call RegPack(RF, InData%AirDens)
   if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLd_UnPackInitOutput(RF, OutData)
   type(RegFile), intent(inout)    :: RF
   type(ExtPtfmLd_InitOutputType), intent(inout) :: OutData
   character(*), parameter            :: RoutineName = 'ExtPtfmLd_UnPackInitOutput'
   integer(B4Ki)   :: LB(1), UB(1)
   integer(IntKi)  :: stat
   logical         :: IsAllocAssoc
   if (RF%ErrStat /= ErrID_None) return
   call RegUnpackAlloc(RF, OutData%WriteOutputHdr); if (RegCheckErr(RF, RoutineName)) return
   call RegUnpackAlloc(RF, OutData%WriteOutputUnt); if (RegCheckErr(RF, RoutineName)) return
   call NWTC_Library_UnpackProgDesc(RF, OutData%Ver) ! Ver 
   call RegUnpack(RF, OutData%AirDens); if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLd_CopyContState(SrcContStateData, DstContStateData, CtrlCode, ErrStat, ErrMsg)
   type(ExtPtfmLd_ContinuousStateType), intent(in) :: SrcContStateData
   type(ExtPtfmLd_ContinuousStateType), intent(inout) :: DstContStateData
   integer(IntKi),  intent(in   ) :: CtrlCode
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_CopyContState'
   ErrStat = ErrID_None
   ErrMsg  = ''
   DstContStateData%blah = SrcContStateData%blah
end subroutine

subroutine ExtPtfmLd_DestroyContState(ContStateData, ErrStat, ErrMsg)
   type(ExtPtfmLd_ContinuousStateType), intent(inout) :: ContStateData
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_DestroyContState'
   ErrStat = ErrID_None
   ErrMsg  = ''
end subroutine

subroutine ExtPtfmLd_PackContState(RF, Indata)
   type(RegFile), intent(inout) :: RF
   type(ExtPtfmLd_ContinuousStateType), intent(in) :: InData
   character(*), parameter         :: RoutineName = 'ExtPtfmLd_PackContState'
   if (RF%ErrStat >= AbortErrLev) return
   call RegPack(RF, InData%blah)
   if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLd_UnPackContState(RF, OutData)
   type(RegFile), intent(inout)    :: RF
   type(ExtPtfmLd_ContinuousStateType), intent(inout) :: OutData
   character(*), parameter            :: RoutineName = 'ExtPtfmLd_UnPackContState'
   if (RF%ErrStat /= ErrID_None) return
   call RegUnpack(RF, OutData%blah); if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLd_CopyDiscState(SrcDiscStateData, DstDiscStateData, CtrlCode, ErrStat, ErrMsg)
   type(ExtPtfmLd_DiscreteStateType), intent(in) :: SrcDiscStateData
   type(ExtPtfmLd_DiscreteStateType), intent(inout) :: DstDiscStateData
   integer(IntKi),  intent(in   ) :: CtrlCode
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_CopyDiscState'
   ErrStat = ErrID_None
   ErrMsg  = ''
   DstDiscStateData%blah = SrcDiscStateData%blah
end subroutine

subroutine ExtPtfmLd_DestroyDiscState(DiscStateData, ErrStat, ErrMsg)
   type(ExtPtfmLd_DiscreteStateType), intent(inout) :: DiscStateData
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_DestroyDiscState'
   ErrStat = ErrID_None
   ErrMsg  = ''
end subroutine

subroutine ExtPtfmLd_PackDiscState(RF, Indata)
   type(RegFile), intent(inout) :: RF
   type(ExtPtfmLd_DiscreteStateType), intent(in) :: InData
   character(*), parameter         :: RoutineName = 'ExtPtfmLd_PackDiscState'
   if (RF%ErrStat >= AbortErrLev) return
   call RegPack(RF, InData%blah)
   if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLd_UnPackDiscState(RF, OutData)
   type(RegFile), intent(inout)    :: RF
   type(ExtPtfmLd_DiscreteStateType), intent(inout) :: OutData
   character(*), parameter            :: RoutineName = 'ExtPtfmLd_UnPackDiscState'
   if (RF%ErrStat /= ErrID_None) return
   call RegUnpack(RF, OutData%blah); if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLd_CopyMisc(SrcMiscData, DstMiscData, CtrlCode, ErrStat, ErrMsg)
   type(ExtPtfmLd_MiscVarType), intent(in) :: SrcMiscData
   type(ExtPtfmLd_MiscVarType), intent(inout) :: DstMiscData
   integer(IntKi),  intent(in   ) :: CtrlCode
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_CopyMisc'
   ErrStat = ErrID_None
   ErrMsg  = ''
   DstMiscData%phi_cfd = SrcMiscData%phi_cfd
end subroutine

subroutine ExtPtfmLd_DestroyMisc(MiscData, ErrStat, ErrMsg)
   type(ExtPtfmLd_MiscVarType), intent(inout) :: MiscData
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_DestroyMisc'
   ErrStat = ErrID_None
   ErrMsg  = ''
end subroutine

subroutine ExtPtfmLd_PackMisc(RF, Indata)
   type(RegFile), intent(inout) :: RF
   type(ExtPtfmLd_MiscVarType), intent(in) :: InData
   character(*), parameter         :: RoutineName = 'ExtPtfmLd_PackMisc'
   if (RF%ErrStat >= AbortErrLev) return
   call RegPack(RF, InData%phi_cfd)
   if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLd_UnPackMisc(RF, OutData)
   type(RegFile), intent(inout)    :: RF
   type(ExtPtfmLd_MiscVarType), intent(inout) :: OutData
   character(*), parameter            :: RoutineName = 'ExtPtfmLd_UnPackMisc'
   if (RF%ErrStat /= ErrID_None) return
   call RegUnpack(RF, OutData%phi_cfd); if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLd_CopyConstrState(SrcConstrStateData, DstConstrStateData, CtrlCode, ErrStat, ErrMsg)
   type(ExtPtfmLd_ConstraintStateType), intent(in) :: SrcConstrStateData
   type(ExtPtfmLd_ConstraintStateType), intent(inout) :: DstConstrStateData
   integer(IntKi),  intent(in   ) :: CtrlCode
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_CopyConstrState'
   ErrStat = ErrID_None
   ErrMsg  = ''
   DstConstrStateData%blah = SrcConstrStateData%blah
end subroutine

subroutine ExtPtfmLd_DestroyConstrState(ConstrStateData, ErrStat, ErrMsg)
   type(ExtPtfmLd_ConstraintStateType), intent(inout) :: ConstrStateData
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_DestroyConstrState'
   ErrStat = ErrID_None
   ErrMsg  = ''
end subroutine

subroutine ExtPtfmLd_PackConstrState(RF, Indata)
   type(RegFile), intent(inout) :: RF
   type(ExtPtfmLd_ConstraintStateType), intent(in) :: InData
   character(*), parameter         :: RoutineName = 'ExtPtfmLd_PackConstrState'
   if (RF%ErrStat >= AbortErrLev) return
   call RegPack(RF, InData%blah)
   if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLd_UnPackConstrState(RF, OutData)
   type(RegFile), intent(inout)    :: RF
   type(ExtPtfmLd_ConstraintStateType), intent(inout) :: OutData
   character(*), parameter            :: RoutineName = 'ExtPtfmLd_UnPackConstrState'
   if (RF%ErrStat /= ErrID_None) return
   call RegUnpack(RF, OutData%blah); if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLd_CopyOtherState(SrcOtherStateData, DstOtherStateData, CtrlCode, ErrStat, ErrMsg)
   type(ExtPtfmLd_OtherStateType), intent(in) :: SrcOtherStateData
   type(ExtPtfmLd_OtherStateType), intent(inout) :: DstOtherStateData
   integer(IntKi),  intent(in   ) :: CtrlCode
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_CopyOtherState'
   ErrStat = ErrID_None
   ErrMsg  = ''
   DstOtherStateData%blah = SrcOtherStateData%blah
end subroutine

subroutine ExtPtfmLd_DestroyOtherState(OtherStateData, ErrStat, ErrMsg)
   type(ExtPtfmLd_OtherStateType), intent(inout) :: OtherStateData
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_DestroyOtherState'
   ErrStat = ErrID_None
   ErrMsg  = ''
end subroutine

subroutine ExtPtfmLd_PackOtherState(RF, Indata)
   type(RegFile), intent(inout) :: RF
   type(ExtPtfmLd_OtherStateType), intent(in) :: InData
   character(*), parameter         :: RoutineName = 'ExtPtfmLd_PackOtherState'
   if (RF%ErrStat >= AbortErrLev) return
   call RegPack(RF, InData%blah)
   if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLd_UnPackOtherState(RF, OutData)
   type(RegFile), intent(inout)    :: RF
   type(ExtPtfmLd_OtherStateType), intent(inout) :: OutData
   character(*), parameter            :: RoutineName = 'ExtPtfmLd_UnPackOtherState'
   if (RF%ErrStat /= ErrID_None) return
   call RegUnpack(RF, OutData%blah); if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLd_CopyParam(SrcParamData, DstParamData, CtrlCode, ErrStat, ErrMsg)
   type(ExtPtfmLd_ParameterType), intent(in) :: SrcParamData
   type(ExtPtfmLd_ParameterType), intent(inout) :: DstParamData
   integer(IntKi),  intent(in   ) :: CtrlCode
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   integer(IntKi)                 :: ErrStat2
   character(ErrMsgLen)           :: ErrMsg2
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_CopyParam'
   ErrStat = ErrID_None
   ErrMsg  = ''
   call ExtPtfmLdDX_CopyParam(SrcParamData%DX_p, DstParamData%DX_p, CtrlCode, ErrStat2, ErrMsg2)
   call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   if (ErrStat >= AbortErrLev) return
end subroutine

subroutine ExtPtfmLd_DestroyParam(ParamData, ErrStat, ErrMsg)
   type(ExtPtfmLd_ParameterType), intent(inout) :: ParamData
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   integer(IntKi)                 :: ErrStat2
   character(ErrMsgLen)           :: ErrMsg2
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_DestroyParam'
   ErrStat = ErrID_None
   ErrMsg  = ''
   call ExtPtfmLdDX_DestroyParam(ParamData%DX_p, ErrStat2, ErrMsg2)
   call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
end subroutine

subroutine ExtPtfmLd_PackParam(RF, Indata)
   type(RegFile), intent(inout) :: RF
   type(ExtPtfmLd_ParameterType), intent(in) :: InData
   character(*), parameter         :: RoutineName = 'ExtPtfmLd_PackParam'
   if (RF%ErrStat >= AbortErrLev) return
   call ExtPtfmLdDX_PackParam(RF, InData%DX_p) 
   if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLd_UnPackParam(RF, OutData)
   type(RegFile), intent(inout)    :: RF
   type(ExtPtfmLd_ParameterType), intent(inout) :: OutData
   character(*), parameter            :: RoutineName = 'ExtPtfmLd_UnPackParam'
   if (RF%ErrStat /= ErrID_None) return
   call ExtPtfmLdDX_UnpackParam(RF, OutData%DX_p) ! DX_p 
end subroutine

subroutine ExtPtfmLd_CopyInput(SrcInputData, DstInputData, CtrlCode, ErrStat, ErrMsg)
   type(ExtPtfmLd_InputType), intent(inout) :: SrcInputData
   type(ExtPtfmLd_InputType), intent(inout) :: DstInputData
   integer(IntKi),  intent(in   ) :: CtrlCode
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   integer(IntKi)                 :: ErrStat2
   character(ErrMsgLen)           :: ErrMsg2
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_CopyInput'
   ErrStat = ErrID_None
   ErrMsg  = ''
   call ExtPtfmLdDX_CopyInput(SrcInputData%DX_u, DstInputData%DX_u, CtrlCode, ErrStat2, ErrMsg2)
   call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   if (ErrStat >= AbortErrLev) return
   call MeshCopy(SrcInputData%PtfmMotion, DstInputData%PtfmMotion, CtrlCode, ErrStat2, ErrMsg2 )
   call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   if (ErrStat >= AbortErrLev) return
end subroutine

subroutine ExtPtfmLd_DestroyInput(InputData, ErrStat, ErrMsg)
   type(ExtPtfmLd_InputType), intent(inout) :: InputData
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   integer(IntKi)                 :: ErrStat2
   character(ErrMsgLen)           :: ErrMsg2
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_DestroyInput'
   ErrStat = ErrID_None
   ErrMsg  = ''
   call ExtPtfmLdDX_DestroyInput(InputData%DX_u, ErrStat2, ErrMsg2)
   call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   call MeshDestroy( InputData%PtfmMotion, ErrStat2, ErrMsg2)
   call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
end subroutine

subroutine ExtPtfmLd_PackInput(RF, Indata)
   type(RegFile), intent(inout) :: RF
   type(ExtPtfmLd_InputType), intent(in) :: InData
   character(*), parameter         :: RoutineName = 'ExtPtfmLd_PackInput'
   if (RF%ErrStat >= AbortErrLev) return
   call ExtPtfmLdDX_PackInput(RF, InData%DX_u) 
   call MeshPack(RF, InData%PtfmMotion) 
   if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLd_UnPackInput(RF, OutData)
   type(RegFile), intent(inout)    :: RF
   type(ExtPtfmLd_InputType), intent(inout) :: OutData
   character(*), parameter            :: RoutineName = 'ExtPtfmLd_UnPackInput'
   if (RF%ErrStat /= ErrID_None) return
   call ExtPtfmLdDX_UnpackInput(RF, OutData%DX_u) ! DX_u 
   call MeshUnpack(RF, OutData%PtfmMotion) ! PtfmMotion 
end subroutine

subroutine ExtPtfmLd_CopyOutput(SrcOutputData, DstOutputData, CtrlCode, ErrStat, ErrMsg)
   type(ExtPtfmLd_OutputType), intent(inout) :: SrcOutputData
   type(ExtPtfmLd_OutputType), intent(inout) :: DstOutputData
   integer(IntKi),  intent(in   ) :: CtrlCode
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   integer(IntKi)                 :: ErrStat2
   character(ErrMsgLen)           :: ErrMsg2
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_CopyOutput'
   ErrStat = ErrID_None
   ErrMsg  = ''
   call ExtPtfmLdDX_CopyOutput(SrcOutputData%DX_y, DstOutputData%DX_y, CtrlCode, ErrStat2, ErrMsg2)
   call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   if (ErrStat >= AbortErrLev) return
   call MeshCopy(SrcOutputData%PtfmMesh, DstOutputData%PtfmMesh, CtrlCode, ErrStat2, ErrMsg2 )
   call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   if (ErrStat >= AbortErrLev) return
end subroutine

subroutine ExtPtfmLd_DestroyOutput(OutputData, ErrStat, ErrMsg)
   type(ExtPtfmLd_OutputType), intent(inout) :: OutputData
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   integer(IntKi)                 :: ErrStat2
   character(ErrMsgLen)           :: ErrMsg2
   character(*), parameter        :: RoutineName = 'ExtPtfmLd_DestroyOutput'
   ErrStat = ErrID_None
   ErrMsg  = ''
   call ExtPtfmLdDX_DestroyOutput(OutputData%DX_y, ErrStat2, ErrMsg2)
   call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   call MeshDestroy( OutputData%PtfmMesh, ErrStat2, ErrMsg2)
   call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
end subroutine

subroutine ExtPtfmLd_PackOutput(RF, Indata)
   type(RegFile), intent(inout) :: RF
   type(ExtPtfmLd_OutputType), intent(in) :: InData
   character(*), parameter         :: RoutineName = 'ExtPtfmLd_PackOutput'
   if (RF%ErrStat >= AbortErrLev) return
   call ExtPtfmLdDX_PackOutput(RF, InData%DX_y) 
   call MeshPack(RF, InData%PtfmMesh) 
   if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLd_UnPackOutput(RF, OutData)
   type(RegFile), intent(inout)    :: RF
   type(ExtPtfmLd_OutputType), intent(inout) :: OutData
   character(*), parameter            :: RoutineName = 'ExtPtfmLd_UnPackOutput'
   if (RF%ErrStat /= ErrID_None) return
   call ExtPtfmLdDX_UnpackOutput(RF, OutData%DX_y) ! DX_y 
   call MeshUnpack(RF, OutData%PtfmMesh) ! PtfmMesh 
end subroutine

subroutine ExtPtfmLd_Input_ExtrapInterp(u, t, u_out, t_out, ErrStat, ErrMsg)
   !
   ! This subroutine calculates a extrapolated (or interpolated) Input u_out at time t_out, from previous/future time
   ! values of u (which has values associated with times in t).  Order of the interpolation is given by the size of u
   !
   !  expressions below based on either
   !
   !  f(t) = a
   !  f(t) = a + b * t, or
   !  f(t) = a + b * t + c * t**2
   !
   !  where a, b and c are determined as the solution to
   !  f(t1) = u1, f(t2) = u2, f(t3) = u3  (as appropriate)
   !
   !----------------------------------------------------------------------------------------------------------------------------------
   
   type(ExtPtfmLd_InputType), intent(inout)  :: u(:) ! Input at t1 > t2 > t3
   real(DbKi),                 intent(in   )  :: t(:)           ! Times associated with the Inputs
   type(ExtPtfmLd_InputType), intent(inout)  :: u_out ! Input at tin_out
   real(DbKi),                 intent(in   )  :: t_out           ! time to be extrap/interp'd to
   integer(IntKi),             intent(  out)  :: ErrStat         ! Error status of the operation
   character(*),               intent(  out)  :: ErrMsg          ! Error message if ErrStat /= ErrID_None
   ! local variables
   integer(IntKi)                             :: order           ! order of polynomial fit (max 2)
   integer(IntKi)                             :: ErrStat2        ! local errors
   character(ErrMsgLen)                       :: ErrMsg2         ! local errors
   character(*),    PARAMETER                 :: RoutineName = 'ExtPtfmLd_Input_ExtrapInterp'
   
   ! Initialize ErrStat
   ErrStat = ErrID_None
   ErrMsg  = ''
   if (size(t) /= size(u)) then
      call SetErrStat(ErrID_Fatal, 'size(t) must equal size(u)', ErrStat, ErrMsg, RoutineName)
      return
   endif
   order = size(u) - 1
   select case (order)
   case (0)
      call ExtPtfmLd_CopyInput(u(1), u_out, MESH_UPDATECOPY, ErrStat2, ErrMsg2)
         call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   case (1)
      call ExtPtfmLd_Input_ExtrapInterp1(u(1), u(2), t, u_out, t_out, ErrStat2, ErrMsg2)
         call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   case (2)
      call ExtPtfmLd_Input_ExtrapInterp2(u(1), u(2), u(3), t, u_out, t_out, ErrStat2, ErrMsg2)
         call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   case default
      call SetErrStat(ErrID_Fatal, 'size(u) must be less than 4 (order must be less than 3).', ErrStat, ErrMsg, RoutineName)
      return
   end select
end subroutine

SUBROUTINE ExtPtfmLd_Input_ExtrapInterp1(u1, u2, tin, u_out, tin_out, ErrStat, ErrMsg )
!
! This subroutine calculates a extrapolated (or interpolated) Input u_out at time t_out, from previous/future time
! values of u (which has values associated with times in t).  Order of the interpolation is 1.
!
!  f(t) = a + b * t, or
!
!  where a and b are determined as the solution to
!  f(t1) = u1, f(t2) = u2
!
!..................................................................................................................................

   TYPE(ExtPtfmLd_InputType), INTENT(INOUT)  :: u1    ! Input at t1 > t2
   TYPE(ExtPtfmLd_InputType), INTENT(INOUT)  :: u2    ! Input at t2 
   REAL(DbKi),         INTENT(IN   )          :: tin(2)   ! Times associated with the Inputs
   TYPE(ExtPtfmLd_InputType), INTENT(INOUT)  :: u_out ! Input at tin_out
   REAL(DbKi),         INTENT(IN   )          :: tin_out  ! time to be extrap/interp'd to
   INTEGER(IntKi),     INTENT(  OUT)          :: ErrStat  ! Error status of the operation
   CHARACTER(*),       INTENT(  OUT)          :: ErrMsg   ! Error message if ErrStat /= ErrID_None
   ! local variables
   REAL(DbKi)                                 :: t(2)     ! Times associated with the Inputs
   REAL(DbKi)                                 :: t_out    ! Time to which to be extrap/interpd
   CHARACTER(*),                    PARAMETER :: RoutineName = 'ExtPtfmLd_Input_ExtrapInterp1'
   REAL(DbKi)                                 :: a1, a2   ! temporary for extrapolation/interpolation
   INTEGER(IntKi)                             :: ErrStat2 ! local errors
   CHARACTER(ErrMsgLen)                       :: ErrMsg2  ! local errors
   ! Initialize ErrStat
   ErrStat = ErrID_None
   ErrMsg  = ''
   ! we'll subtract a constant from the times to resolve some 
   ! numerical issues when t gets large (and to simplify the equations)
   t = tin - tin(1)
   t_out = tin_out - tin(1)
   
   IF (EqualRealNos(t(1), t(2))) THEN
      CALL SetErrStat(ErrID_Fatal, 't(1) must not equal t(2) to avoid a division-by-zero error.', ErrStat, ErrMsg, RoutineName)
      RETURN
   END IF
   
   ! Calculate weighting factors from Lagrange polynomial
   a1 = -(t_out - t(2))/t(2)
   a2 = t_out/t(2)
   
   CALL ExtPtfmLdDX_Input_ExtrapInterp1( u1%DX_u, u2%DX_u, tin, u_out%DX_u, tin_out, ErrStat2, ErrMsg2)
      CALL SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg,RoutineName)
   CALL MeshExtrapInterp1(u1%PtfmMotion, u2%PtfmMotion, tin, u_out%PtfmMotion, tin_out, ErrStat2, ErrMsg2)
      CALL SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg,RoutineName)
END SUBROUTINE

SUBROUTINE ExtPtfmLd_Input_ExtrapInterp2(u1, u2, u3, tin, u_out, tin_out, ErrStat, ErrMsg )
!
! This subroutine calculates a extrapolated (or interpolated) Input u_out at time t_out, from previous/future time
! values of u (which has values associated with times in t).  Order of the interpolation is 2.
!
!  expressions below based on either
!
!  f(t) = a + b * t + c * t**2
!
!  where a, b and c are determined as the solution to
!  f(t1) = u1, f(t2) = u2, f(t3) = u3
!
!..................................................................................................................................

   TYPE(ExtPtfmLd_InputType), INTENT(INOUT)  :: u1      ! Input at t1 > t2 > t3
   TYPE(ExtPtfmLd_InputType), INTENT(INOUT)  :: u2      ! Input at t2 > t3
   TYPE(ExtPtfmLd_InputType), INTENT(INOUT)  :: u3      ! Input at t3
   REAL(DbKi),                 INTENT(IN   )  :: tin(3)    ! Times associated with the Inputs
   TYPE(ExtPtfmLd_InputType), INTENT(INOUT)  :: u_out     ! Input at tin_out
   REAL(DbKi),                 INTENT(IN   )  :: tin_out   ! time to be extrap/interp'd to
   INTEGER(IntKi),             INTENT(  OUT)  :: ErrStat   ! Error status of the operation
   CHARACTER(*),               INTENT(  OUT)  :: ErrMsg    ! Error message if ErrStat /= ErrID_None
   ! local variables
   REAL(DbKi)                                 :: t(3)      ! Times associated with the Inputs
   REAL(DbKi)                                 :: t_out     ! Time to which to be extrap/interpd
   INTEGER(IntKi)                             :: order     ! order of polynomial fit (max 2)
   REAL(DbKi)                                 :: a1,a2,a3 ! temporary for extrapolation/interpolation
   INTEGER(IntKi)                             :: ErrStat2 ! local errors
   CHARACTER(ErrMsgLen)                       :: ErrMsg2  ! local errors
   CHARACTER(*),            PARAMETER         :: RoutineName = 'ExtPtfmLd_Input_ExtrapInterp2'
   ! Initialize ErrStat
   ErrStat = ErrID_None
   ErrMsg  = ''
   ! we'll subtract a constant from the times to resolve some 
   ! numerical issues when t gets large (and to simplify the equations)
   t = tin - tin(1)
   t_out = tin_out - tin(1)
   
   IF ( EqualRealNos( t(1), t(2) ) ) THEN
      CALL SetErrStat(ErrID_Fatal, 't(1) must not equal t(2) to avoid a division-by-zero error.', ErrStat, ErrMsg,RoutineName)
      RETURN
   ELSE IF ( EqualRealNos( t(2), t(3) ) ) THEN
      CALL SetErrStat(ErrID_Fatal, 't(2) must not equal t(3) to avoid a division-by-zero error.', ErrStat, ErrMsg,RoutineName)
      RETURN
   ELSE IF ( EqualRealNos( t(1), t(3) ) ) THEN
      CALL SetErrStat(ErrID_Fatal, 't(1) must not equal t(3) to avoid a division-by-zero error.', ErrStat, ErrMsg,RoutineName)
      RETURN
   END IF
   
   ! Calculate Lagrange polynomial coefficients
   a1 = (t_out - t(2))*(t_out - t(3))/((t(1) - t(2))*(t(1) - t(3)))
   a2 = (t_out - t(1))*(t_out - t(3))/((t(2) - t(1))*(t(2) - t(3)))
   a3 = (t_out - t(1))*(t_out - t(2))/((t(3) - t(1))*(t(3) - t(2)))
   CALL ExtPtfmLdDX_Input_ExtrapInterp2( u1%DX_u, u2%DX_u, u3%DX_u, tin, u_out%DX_u, tin_out, ErrStat2, ErrMsg2)
      CALL SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg,RoutineName)
   CALL MeshExtrapInterp2(u1%PtfmMotion, u2%PtfmMotion, u3%PtfmMotion, tin, u_out%PtfmMotion, tin_out, ErrStat2, ErrMsg2)
      CALL SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg,RoutineName)
END SUBROUTINE

subroutine ExtPtfmLd_Output_ExtrapInterp(y, t, y_out, t_out, ErrStat, ErrMsg)
   !
   ! This subroutine calculates a extrapolated (or interpolated) Output y_out at time t_out, from previous/future time
   ! values of y (which has values associated with times in t).  Order of the interpolation is given by the size of y
   !
   !  expressions below based on either
   !
   !  f(t) = a
   !  f(t) = a + b * t, or
   !  f(t) = a + b * t + c * t**2
   !
   !  where a, b and c are determined as the solution to
   !  f(t1) = y1, f(t2) = y2, f(t3) = y3  (as appropriate)
   !
   !----------------------------------------------------------------------------------------------------------------------------------
   
   type(ExtPtfmLd_OutputType), intent(inout)  :: y(:) ! Output at t1 > t2 > t3
   real(DbKi),                 intent(in   )  :: t(:)           ! Times associated with the Outputs
   type(ExtPtfmLd_OutputType), intent(inout)  :: y_out ! Output at tin_out
   real(DbKi),                 intent(in   )  :: t_out           ! time to be extrap/interp'd to
   integer(IntKi),             intent(  out)  :: ErrStat         ! Error status of the operation
   character(*),               intent(  out)  :: ErrMsg          ! Error message if ErrStat /= ErrID_None
   ! local variables
   integer(IntKi)                             :: order           ! order of polynomial fit (max 2)
   integer(IntKi)                             :: ErrStat2        ! local errors
   character(ErrMsgLen)                       :: ErrMsg2         ! local errors
   character(*),    PARAMETER                 :: RoutineName = 'ExtPtfmLd_Output_ExtrapInterp'
   
   ! Initialize ErrStat
   ErrStat = ErrID_None
   ErrMsg  = ''
   if (size(t) /= size(y)) then
      call SetErrStat(ErrID_Fatal, 'size(t) must equal size(y)', ErrStat, ErrMsg, RoutineName)
      return
   endif
   order = size(y) - 1
   select case (order)
   case (0)
      call ExtPtfmLd_CopyOutput(y(1), y_out, MESH_UPDATECOPY, ErrStat2, ErrMsg2)
         call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   case (1)
      call ExtPtfmLd_Output_ExtrapInterp1(y(1), y(2), t, y_out, t_out, ErrStat2, ErrMsg2)
         call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   case (2)
      call ExtPtfmLd_Output_ExtrapInterp2(y(1), y(2), y(3), t, y_out, t_out, ErrStat2, ErrMsg2)
         call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   case default
      call SetErrStat(ErrID_Fatal, 'size(y) must be less than 4 (order must be less than 3).', ErrStat, ErrMsg, RoutineName)
      return
   end select
end subroutine

SUBROUTINE ExtPtfmLd_Output_ExtrapInterp1(y1, y2, tin, y_out, tin_out, ErrStat, ErrMsg )
!
! This subroutine calculates a extrapolated (or interpolated) Output y_out at time t_out, from previous/future time
! values of y (which has values associated with times in t).  Order of the interpolation is 1.
!
!  f(t) = a + b * t, or
!
!  where a and b are determined as the solution to
!  f(t1) = y1, f(t2) = y2
!
!..................................................................................................................................

   TYPE(ExtPtfmLd_OutputType), INTENT(INOUT)  :: y1    ! Output at t1 > t2
   TYPE(ExtPtfmLd_OutputType), INTENT(INOUT)  :: y2    ! Output at t2 
   REAL(DbKi),         INTENT(IN   )          :: tin(2)   ! Times associated with the Outputs
   TYPE(ExtPtfmLd_OutputType), INTENT(INOUT)  :: y_out ! Output at tin_out
   REAL(DbKi),         INTENT(IN   )          :: tin_out  ! time to be extrap/interp'd to
   INTEGER(IntKi),     INTENT(  OUT)          :: ErrStat  ! Error status of the operation
   CHARACTER(*),       INTENT(  OUT)          :: ErrMsg   ! Error message if ErrStat /= ErrID_None
   ! local variables
   REAL(DbKi)                                 :: t(2)     ! Times associated with the Outputs
   REAL(DbKi)                                 :: t_out    ! Time to which to be extrap/interpd
   CHARACTER(*),                    PARAMETER :: RoutineName = 'ExtPtfmLd_Output_ExtrapInterp1'
   REAL(DbKi)                                 :: a1, a2   ! temporary for extrapolation/interpolation
   INTEGER(IntKi)                             :: ErrStat2 ! local errors
   CHARACTER(ErrMsgLen)                       :: ErrMsg2  ! local errors
   ! Initialize ErrStat
   ErrStat = ErrID_None
   ErrMsg  = ''
   ! we'll subtract a constant from the times to resolve some 
   ! numerical issues when t gets large (and to simplify the equations)
   t = tin - tin(1)
   t_out = tin_out - tin(1)
   
   IF (EqualRealNos(t(1), t(2))) THEN
      CALL SetErrStat(ErrID_Fatal, 't(1) must not equal t(2) to avoid a division-by-zero error.', ErrStat, ErrMsg, RoutineName)
      RETURN
   END IF
   
   ! Calculate weighting factors from Lagrange polynomial
   a1 = -(t_out - t(2))/t(2)
   a2 = t_out/t(2)
   
   CALL ExtPtfmLdDX_Output_ExtrapInterp1( y1%DX_y, y2%DX_y, tin, y_out%DX_y, tin_out, ErrStat2, ErrMsg2)
      CALL SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg,RoutineName)
   CALL MeshExtrapInterp1(y1%PtfmMesh, y2%PtfmMesh, tin, y_out%PtfmMesh, tin_out, ErrStat2, ErrMsg2)
      CALL SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg,RoutineName)
END SUBROUTINE

SUBROUTINE ExtPtfmLd_Output_ExtrapInterp2(y1, y2, y3, tin, y_out, tin_out, ErrStat, ErrMsg )
!
! This subroutine calculates a extrapolated (or interpolated) Output y_out at time t_out, from previous/future time
! values of y (which has values associated with times in t).  Order of the interpolation is 2.
!
!  expressions below based on either
!
!  f(t) = a + b * t + c * t**2
!
!  where a, b and c are determined as the solution to
!  f(t1) = y1, f(t2) = y2, f(t3) = y3
!
!..................................................................................................................................

   TYPE(ExtPtfmLd_OutputType), INTENT(INOUT)  :: y1      ! Output at t1 > t2 > t3
   TYPE(ExtPtfmLd_OutputType), INTENT(INOUT)  :: y2      ! Output at t2 > t3
   TYPE(ExtPtfmLd_OutputType), INTENT(INOUT)  :: y3      ! Output at t3
   REAL(DbKi),                 INTENT(IN   )  :: tin(3)    ! Times associated with the Outputs
   TYPE(ExtPtfmLd_OutputType), INTENT(INOUT)  :: y_out     ! Output at tin_out
   REAL(DbKi),                 INTENT(IN   )  :: tin_out   ! time to be extrap/interp'd to
   INTEGER(IntKi),             INTENT(  OUT)  :: ErrStat   ! Error status of the operation
   CHARACTER(*),               INTENT(  OUT)  :: ErrMsg    ! Error message if ErrStat /= ErrID_None
   ! local variables
   REAL(DbKi)                                 :: t(3)      ! Times associated with the Outputs
   REAL(DbKi)                                 :: t_out     ! Time to which to be extrap/interpd
   INTEGER(IntKi)                             :: order     ! order of polynomial fit (max 2)
   REAL(DbKi)                                 :: a1,a2,a3 ! temporary for extrapolation/interpolation
   INTEGER(IntKi)                             :: ErrStat2 ! local errors
   CHARACTER(ErrMsgLen)                       :: ErrMsg2  ! local errors
   CHARACTER(*),            PARAMETER         :: RoutineName = 'ExtPtfmLd_Output_ExtrapInterp2'
   ! Initialize ErrStat
   ErrStat = ErrID_None
   ErrMsg  = ''
   ! we'll subtract a constant from the times to resolve some 
   ! numerical issues when t gets large (and to simplify the equations)
   t = tin - tin(1)
   t_out = tin_out - tin(1)
   
   IF ( EqualRealNos( t(1), t(2) ) ) THEN
      CALL SetErrStat(ErrID_Fatal, 't(1) must not equal t(2) to avoid a division-by-zero error.', ErrStat, ErrMsg,RoutineName)
      RETURN
   ELSE IF ( EqualRealNos( t(2), t(3) ) ) THEN
      CALL SetErrStat(ErrID_Fatal, 't(2) must not equal t(3) to avoid a division-by-zero error.', ErrStat, ErrMsg,RoutineName)
      RETURN
   ELSE IF ( EqualRealNos( t(1), t(3) ) ) THEN
      CALL SetErrStat(ErrID_Fatal, 't(1) must not equal t(3) to avoid a division-by-zero error.', ErrStat, ErrMsg,RoutineName)
      RETURN
   END IF
   
   ! Calculate Lagrange polynomial coefficients
   a1 = (t_out - t(2))*(t_out - t(3))/((t(1) - t(2))*(t(1) - t(3)))
   a2 = (t_out - t(1))*(t_out - t(3))/((t(2) - t(1))*(t(2) - t(3)))
   a3 = (t_out - t(1))*(t_out - t(2))/((t(3) - t(1))*(t(3) - t(2)))
   CALL ExtPtfmLdDX_Output_ExtrapInterp2( y1%DX_y, y2%DX_y, y3%DX_y, tin, y_out%DX_y, tin_out, ErrStat2, ErrMsg2)
      CALL SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg,RoutineName)
   CALL MeshExtrapInterp2(y1%PtfmMesh, y2%PtfmMesh, y3%PtfmMesh, tin, y_out%PtfmMesh, tin_out, ErrStat2, ErrMsg2)
      CALL SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg,RoutineName)
END SUBROUTINE
END MODULE ExtPtfmLoads_Types
!ENDOFREGISTRYGENERATEDFILE
