!STARTOFREGISTRYGENERATEDFILE 'ExtPtfmLoadsDX_Types.f90'
!
! WARNING This file is generated automatically by the FAST registry.
! Do not edit.  Your changes to this file will be lost.
!
! FAST Registry
!*********************************************************************************************************************************
! ExtPtfmLoadsDX_Types
!.................................................................................................................................
! This file is part of ExtPtfmLoadsDX.
!
! Copyright (C) 2012-2016 National Renewable Energy Laboratory
!
! Licensed under the Apache License, Version 2.0 (the "License");
! you may not use this file except in compliance with the License.
! You may obtain a copy of the License at
!
!     http://www.apache.org/licenses/LICENSE-2.0
!
! Unless required by applicable law or agreed to in writing, software
! distributed under the License is distributed on an "AS IS" BASIS,
! WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
! See the License for the specific language governing permissions and
! limitations under the License.
!
!
! W A R N I N G : This file was automatically generated from the FAST registry.  Changes made to this file may be lost.
!
!*********************************************************************************************************************************
!> This module contains the user-defined types needed in ExtPtfmLoadsDX. It also contains copy, destroy, pack, and
!! unpack routines associated with each defined data type. This code is automatically generated by the FAST Registry.
MODULE ExtPtfmLoadsDX_Types
!---------------------------------------------------------------------------------------------------------------------------------
USE NWTC_Library
IMPLICIT NONE
! =========  ExtPtfmLdDX_InputType_C  =======
  TYPE, BIND(C) :: ExtPtfmLdDX_InputType_C
   TYPE(C_PTR) :: object = C_NULL_PTR
    TYPE(C_ptr) :: ptfmDef = C_NULL_PTR 
    INTEGER(C_int) :: ptfmDef_Len = 0 
  END TYPE ExtPtfmLdDX_InputType_C
  TYPE, PUBLIC :: ExtPtfmLdDX_InputType
    TYPE( ExtPtfmLdDX_InputType_C ) :: C_obj
    REAL(KIND=C_DOUBLE) , DIMENSION(:), POINTER  :: ptfmDef => NULL()      !< Deformations on the tower  - to send to external driver [-]
  END TYPE ExtPtfmLdDX_InputType
! =======================
! =========  ExtPtfmLdDX_ParameterType_C  =======
  TYPE, BIND(C) :: ExtPtfmLdDX_ParameterType_C
   TYPE(C_PTR) :: object = C_NULL_PTR
    TYPE(C_ptr) :: ptfmRefPos = C_NULL_PTR 
    INTEGER(C_int) :: ptfmRefPos_Len = 0 
  END TYPE ExtPtfmLdDX_ParameterType_C
  TYPE, PUBLIC :: ExtPtfmLdDX_ParameterType
    TYPE( ExtPtfmLdDX_ParameterType_C ) :: C_obj
    REAL(KIND=C_DOUBLE) , DIMENSION(:), POINTER  :: ptfmRefPos => NULL()      !< Reference position of the platform [-]
  END TYPE ExtPtfmLdDX_ParameterType
! =======================
! =========  ExtPtfmLdDX_OutputType_C  =======
  TYPE, BIND(C) :: ExtPtfmLdDX_OutputType_C
   TYPE(C_PTR) :: object = C_NULL_PTR
    TYPE(C_ptr) :: ptfmLd = C_NULL_PTR 
    INTEGER(C_int) :: ptfmLd_Len = 0 
  END TYPE ExtPtfmLdDX_OutputType_C
  TYPE, PUBLIC :: ExtPtfmLdDX_OutputType
    TYPE( ExtPtfmLdDX_OutputType_C ) :: C_obj
    REAL(KIND=C_DOUBLE) , DIMENSION(:), POINTER  :: ptfmLd => NULL()      !< Loads on the platform  - Externally supplied [-]
  END TYPE ExtPtfmLdDX_OutputType
! =======================
CONTAINS

subroutine ExtPtfmLdDX_CopyInput(SrcInputData, DstInputData, CtrlCode, ErrStat, ErrMsg)
   type(ExtPtfmLdDX_InputType), intent(in) :: SrcInputData
   type(ExtPtfmLdDX_InputType), intent(inout) :: DstInputData
   integer(IntKi),  intent(in   ) :: CtrlCode
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   integer(B4Ki)                  :: LB(1), UB(1)
   integer(IntKi)                 :: ErrStat2
   character(*), parameter        :: RoutineName = 'ExtPtfmLdDX_CopyInput'
   ErrStat = ErrID_None
   ErrMsg  = ''
   if (associated(SrcInputData%ptfmDef)) then
      LB(1:1) = lbound(SrcInputData%ptfmDef)
      UB(1:1) = ubound(SrcInputData%ptfmDef)
      if (.not. associated(DstInputData%ptfmDef)) then
         allocate(DstInputData%ptfmDef(LB(1):UB(1)), stat=ErrStat2)
         if (ErrStat2 /= 0) then
            call SetErrStat(ErrID_Fatal, 'Error allocating DstInputData%ptfmDef.', ErrStat, ErrMsg, RoutineName)
            return
         end if
         DstInputData%C_obj%ptfmDef_Len = size(DstInputData%ptfmDef)
         if (DstInputData%C_obj%ptfmDef_Len > 0) &
            DstInputData%C_obj%ptfmDef = c_loc(DstInputData%ptfmDef(LB(1)))
      end if
      DstInputData%ptfmDef = SrcInputData%ptfmDef
   end if
end subroutine

subroutine ExtPtfmLdDX_DestroyInput(InputData, ErrStat, ErrMsg)
   type(ExtPtfmLdDX_InputType), intent(inout) :: InputData
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   character(*), parameter        :: RoutineName = 'ExtPtfmLdDX_DestroyInput'
   ErrStat = ErrID_None
   ErrMsg  = ''
   if (associated(InputData%ptfmDef)) then
      deallocate(InputData%ptfmDef)
      InputData%ptfmDef => null()
      InputData%C_obj%ptfmDef = c_null_ptr
      InputData%C_obj%ptfmDef_Len = 0
   end if
end subroutine

subroutine ExtPtfmLdDX_PackInput(RF, Indata)
   type(RegFile), intent(inout) :: RF
   type(ExtPtfmLdDX_InputType), intent(in) :: InData
   character(*), parameter         :: RoutineName = 'ExtPtfmLdDX_PackInput'
   logical         :: PtrInIndex
   if (RF%ErrStat >= AbortErrLev) return
   if (c_associated(InData%C_obj%object)) then
      RF%ErrStat = ErrID_Fatal
      RF%ErrMsg = RoutineName//': C_obj%object cannot be packed.'
      return
   end if
   call RegPackPtr(RF, InData%ptfmDef)
   if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLdDX_UnPackInput(RF, OutData)
   type(RegFile), intent(inout)    :: RF
   type(ExtPtfmLdDX_InputType), intent(inout) :: OutData
   character(*), parameter            :: RoutineName = 'ExtPtfmLdDX_UnPackInput'
   integer(B4Ki)   :: LB(1), UB(1)
   integer(IntKi)  :: stat
   logical         :: IsAllocAssoc
   integer(B8Ki)   :: PtrIdx
   type(c_ptr)     :: Ptr
   if (RF%ErrStat /= ErrID_None) return
   call RegUnpackPtr(RF, OutData%ptfmDef, LB, UB); if (RegCheckErr(RF, RoutineName)) return
   if (associated(OutData%ptfmDef)) then
      OutData%C_obj%ptfmDef_Len = size(OutData%ptfmDef)
      if (OutData%C_obj%ptfmDef_Len > 0) OutData%C_obj%ptfmDef = c_loc(OutData%ptfmDef(LB(1)))
   end if
end subroutine

SUBROUTINE ExtPtfmLdDX_C2Fary_CopyInput(InputData, ErrStat, ErrMsg, SkipPointers)
   TYPE(ExtPtfmLdDX_InputType), INTENT(INOUT) :: InputData
   INTEGER(IntKi),  INTENT(  OUT) :: ErrStat
   CHARACTER(*),    INTENT(  OUT) :: ErrMsg
   LOGICAL,OPTIONAL,INTENT(IN   ) :: SkipPointers
   ! 
   LOGICAL                        :: SkipPointers_local
   ErrStat = ErrID_None
   ErrMsg  = ""
   
   IF (PRESENT(SkipPointers)) THEN
      SkipPointers_local = SkipPointers
   ELSE
      SkipPointers_local = .false.
   END IF
   
   ! -- ptfmDef Input Data fields
   IF ( .NOT. SkipPointers_local ) THEN
      IF ( .NOT. C_ASSOCIATED( InputData%C_obj%ptfmDef ) ) THEN
         NULLIFY( InputData%ptfmDef )
      ELSE
         CALL C_F_POINTER(InputData%C_obj%ptfmDef, InputData%ptfmDef, [InputData%C_obj%ptfmDef_Len])
      END IF
   END IF
END SUBROUTINE

SUBROUTINE ExtPtfmLdDX_F2C_CopyInput( InputData, ErrStat, ErrMsg, SkipPointers  )
   TYPE(ExtPtfmLdDX_InputType), INTENT(INOUT) :: InputData
   INTEGER(IntKi),  INTENT(  OUT) :: ErrStat
   CHARACTER(*),    INTENT(  OUT) :: ErrMsg
   LOGICAL,OPTIONAL,INTENT(IN   ) :: SkipPointers
   ! 
   LOGICAL                        :: SkipPointers_local
   ErrStat = ErrID_None
   ErrMsg  = ''
   
   IF (PRESENT(SkipPointers)) THEN
      SkipPointers_local = SkipPointers
   ELSE
      SkipPointers_local = .false.
   END IF
   
   ! -- ptfmDef Input Data fields
   IF (.NOT. SkipPointers_local ) THEN
      IF (.NOT. ASSOCIATED(InputData%ptfmDef)) THEN 
         InputData%C_obj%ptfmDef_Len = 0
         InputData%C_obj%ptfmDef = C_NULL_PTR
      ELSE
         InputData%C_obj%ptfmDef_Len = SIZE(InputData%ptfmDef)
         IF (InputData%C_obj%ptfmDef_Len > 0) &
            InputData%C_obj%ptfmDef = C_LOC(InputData%ptfmDef(lbound(InputData%ptfmDef,1)))
      END IF
   END IF
END SUBROUTINE

subroutine ExtPtfmLdDX_CopyParam(SrcParamData, DstParamData, CtrlCode, ErrStat, ErrMsg)
   type(ExtPtfmLdDX_ParameterType), intent(in) :: SrcParamData
   type(ExtPtfmLdDX_ParameterType), intent(inout) :: DstParamData
   integer(IntKi),  intent(in   ) :: CtrlCode
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   integer(B4Ki)                  :: LB(1), UB(1)
   integer(IntKi)                 :: ErrStat2
   character(*), parameter        :: RoutineName = 'ExtPtfmLdDX_CopyParam'
   ErrStat = ErrID_None
   ErrMsg  = ''
   if (associated(SrcParamData%ptfmRefPos)) then
      LB(1:1) = lbound(SrcParamData%ptfmRefPos)
      UB(1:1) = ubound(SrcParamData%ptfmRefPos)
      if (.not. associated(DstParamData%ptfmRefPos)) then
         allocate(DstParamData%ptfmRefPos(LB(1):UB(1)), stat=ErrStat2)
         if (ErrStat2 /= 0) then
            call SetErrStat(ErrID_Fatal, 'Error allocating DstParamData%ptfmRefPos.', ErrStat, ErrMsg, RoutineName)
            return
         end if
         DstParamData%C_obj%ptfmRefPos_Len = size(DstParamData%ptfmRefPos)
         if (DstParamData%C_obj%ptfmRefPos_Len > 0) &
            DstParamData%C_obj%ptfmRefPos = c_loc(DstParamData%ptfmRefPos(LB(1)))
      end if
      DstParamData%ptfmRefPos = SrcParamData%ptfmRefPos
   end if
end subroutine

subroutine ExtPtfmLdDX_DestroyParam(ParamData, ErrStat, ErrMsg)
   type(ExtPtfmLdDX_ParameterType), intent(inout) :: ParamData
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   character(*), parameter        :: RoutineName = 'ExtPtfmLdDX_DestroyParam'
   ErrStat = ErrID_None
   ErrMsg  = ''
   if (associated(ParamData%ptfmRefPos)) then
      deallocate(ParamData%ptfmRefPos)
      ParamData%ptfmRefPos => null()
      ParamData%C_obj%ptfmRefPos = c_null_ptr
      ParamData%C_obj%ptfmRefPos_Len = 0
   end if
end subroutine

subroutine ExtPtfmLdDX_PackParam(RF, Indata)
   type(RegFile), intent(inout) :: RF
   type(ExtPtfmLdDX_ParameterType), intent(in) :: InData
   character(*), parameter         :: RoutineName = 'ExtPtfmLdDX_PackParam'
   logical         :: PtrInIndex
   if (RF%ErrStat >= AbortErrLev) return
   if (c_associated(InData%C_obj%object)) then
      RF%ErrStat = ErrID_Fatal
      RF%ErrMsg = RoutineName//': C_obj%object cannot be packed.'
      return
   end if
   call RegPackPtr(RF, InData%ptfmRefPos)
   if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLdDX_UnPackParam(RF, OutData)
   type(RegFile), intent(inout)    :: RF
   type(ExtPtfmLdDX_ParameterType), intent(inout) :: OutData
   character(*), parameter            :: RoutineName = 'ExtPtfmLdDX_UnPackParam'
   integer(B4Ki)   :: LB(1), UB(1)
   integer(IntKi)  :: stat
   logical         :: IsAllocAssoc
   integer(B8Ki)   :: PtrIdx
   type(c_ptr)     :: Ptr
   if (RF%ErrStat /= ErrID_None) return
   call RegUnpackPtr(RF, OutData%ptfmRefPos, LB, UB); if (RegCheckErr(RF, RoutineName)) return
   if (associated(OutData%ptfmRefPos)) then
      OutData%C_obj%ptfmRefPos_Len = size(OutData%ptfmRefPos)
      if (OutData%C_obj%ptfmRefPos_Len > 0) OutData%C_obj%ptfmRefPos = c_loc(OutData%ptfmRefPos(LB(1)))
   end if
end subroutine

SUBROUTINE ExtPtfmLdDX_C2Fary_CopyParam(ParamData, ErrStat, ErrMsg, SkipPointers)
   TYPE(ExtPtfmLdDX_ParameterType), INTENT(INOUT) :: ParamData
   INTEGER(IntKi),  INTENT(  OUT) :: ErrStat
   CHARACTER(*),    INTENT(  OUT) :: ErrMsg
   LOGICAL,OPTIONAL,INTENT(IN   ) :: SkipPointers
   ! 
   LOGICAL                        :: SkipPointers_local
   ErrStat = ErrID_None
   ErrMsg  = ""
   
   IF (PRESENT(SkipPointers)) THEN
      SkipPointers_local = SkipPointers
   ELSE
      SkipPointers_local = .false.
   END IF
   
   ! -- ptfmRefPos Param Data fields
   IF ( .NOT. SkipPointers_local ) THEN
      IF ( .NOT. C_ASSOCIATED( ParamData%C_obj%ptfmRefPos ) ) THEN
         NULLIFY( ParamData%ptfmRefPos )
      ELSE
         CALL C_F_POINTER(ParamData%C_obj%ptfmRefPos, ParamData%ptfmRefPos, [ParamData%C_obj%ptfmRefPos_Len])
      END IF
   END IF
END SUBROUTINE

SUBROUTINE ExtPtfmLdDX_F2C_CopyParam( ParamData, ErrStat, ErrMsg, SkipPointers  )
   TYPE(ExtPtfmLdDX_ParameterType), INTENT(INOUT) :: ParamData
   INTEGER(IntKi),  INTENT(  OUT) :: ErrStat
   CHARACTER(*),    INTENT(  OUT) :: ErrMsg
   LOGICAL,OPTIONAL,INTENT(IN   ) :: SkipPointers
   ! 
   LOGICAL                        :: SkipPointers_local
   ErrStat = ErrID_None
   ErrMsg  = ''
   
   IF (PRESENT(SkipPointers)) THEN
      SkipPointers_local = SkipPointers
   ELSE
      SkipPointers_local = .false.
   END IF
   
   ! -- ptfmRefPos Param Data fields
   IF (.NOT. SkipPointers_local ) THEN
      IF (.NOT. ASSOCIATED(ParamData%ptfmRefPos)) THEN 
         ParamData%C_obj%ptfmRefPos_Len = 0
         ParamData%C_obj%ptfmRefPos = C_NULL_PTR
      ELSE
         ParamData%C_obj%ptfmRefPos_Len = SIZE(ParamData%ptfmRefPos)
         IF (ParamData%C_obj%ptfmRefPos_Len > 0) &
            ParamData%C_obj%ptfmRefPos = C_LOC(ParamData%ptfmRefPos(lbound(ParamData%ptfmRefPos,1)))
      END IF
   END IF
END SUBROUTINE

subroutine ExtPtfmLdDX_CopyOutput(SrcOutputData, DstOutputData, CtrlCode, ErrStat, ErrMsg)
   type(ExtPtfmLdDX_OutputType), intent(in) :: SrcOutputData
   type(ExtPtfmLdDX_OutputType), intent(inout) :: DstOutputData
   integer(IntKi),  intent(in   ) :: CtrlCode
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   integer(B4Ki)                  :: LB(1), UB(1)
   integer(IntKi)                 :: ErrStat2
   character(*), parameter        :: RoutineName = 'ExtPtfmLdDX_CopyOutput'
   ErrStat = ErrID_None
   ErrMsg  = ''
   if (associated(SrcOutputData%ptfmLd)) then
      LB(1:1) = lbound(SrcOutputData%ptfmLd)
      UB(1:1) = ubound(SrcOutputData%ptfmLd)
      if (.not. associated(DstOutputData%ptfmLd)) then
         allocate(DstOutputData%ptfmLd(LB(1):UB(1)), stat=ErrStat2)
         if (ErrStat2 /= 0) then
            call SetErrStat(ErrID_Fatal, 'Error allocating DstOutputData%ptfmLd.', ErrStat, ErrMsg, RoutineName)
            return
         end if
         DstOutputData%C_obj%ptfmLd_Len = size(DstOutputData%ptfmLd)
         if (DstOutputData%C_obj%ptfmLd_Len > 0) &
            DstOutputData%C_obj%ptfmLd = c_loc(DstOutputData%ptfmLd(LB(1)))
      end if
      DstOutputData%ptfmLd = SrcOutputData%ptfmLd
   end if
end subroutine

subroutine ExtPtfmLdDX_DestroyOutput(OutputData, ErrStat, ErrMsg)
   type(ExtPtfmLdDX_OutputType), intent(inout) :: OutputData
   integer(IntKi),  intent(  out) :: ErrStat
   character(*),    intent(  out) :: ErrMsg
   character(*), parameter        :: RoutineName = 'ExtPtfmLdDX_DestroyOutput'
   ErrStat = ErrID_None
   ErrMsg  = ''
   if (associated(OutputData%ptfmLd)) then
      deallocate(OutputData%ptfmLd)
      OutputData%ptfmLd => null()
      OutputData%C_obj%ptfmLd = c_null_ptr
      OutputData%C_obj%ptfmLd_Len = 0
   end if
end subroutine

subroutine ExtPtfmLdDX_PackOutput(RF, Indata)
   type(RegFile), intent(inout) :: RF
   type(ExtPtfmLdDX_OutputType), intent(in) :: InData
   character(*), parameter         :: RoutineName = 'ExtPtfmLdDX_PackOutput'
   logical         :: PtrInIndex
   if (RF%ErrStat >= AbortErrLev) return
   if (c_associated(InData%C_obj%object)) then
      RF%ErrStat = ErrID_Fatal
      RF%ErrMsg = RoutineName//': C_obj%object cannot be packed.'
      return
   end if
   call RegPackPtr(RF, InData%ptfmLd)
   if (RegCheckErr(RF, RoutineName)) return
end subroutine

subroutine ExtPtfmLdDX_UnPackOutput(RF, OutData)
   type(RegFile), intent(inout)    :: RF
   type(ExtPtfmLdDX_OutputType), intent(inout) :: OutData
   character(*), parameter            :: RoutineName = 'ExtPtfmLdDX_UnPackOutput'
   integer(B4Ki)   :: LB(1), UB(1)
   integer(IntKi)  :: stat
   logical         :: IsAllocAssoc
   integer(B8Ki)   :: PtrIdx
   type(c_ptr)     :: Ptr
   if (RF%ErrStat /= ErrID_None) return
   call RegUnpackPtr(RF, OutData%ptfmLd, LB, UB); if (RegCheckErr(RF, RoutineName)) return
   if (associated(OutData%ptfmLd)) then
      OutData%C_obj%ptfmLd_Len = size(OutData%ptfmLd)
      if (OutData%C_obj%ptfmLd_Len > 0) OutData%C_obj%ptfmLd = c_loc(OutData%ptfmLd(LB(1)))
   end if
end subroutine

SUBROUTINE ExtPtfmLdDX_C2Fary_CopyOutput(OutputData, ErrStat, ErrMsg, SkipPointers)
   TYPE(ExtPtfmLdDX_OutputType), INTENT(INOUT) :: OutputData
   INTEGER(IntKi),  INTENT(  OUT) :: ErrStat
   CHARACTER(*),    INTENT(  OUT) :: ErrMsg
   LOGICAL,OPTIONAL,INTENT(IN   ) :: SkipPointers
   ! 
   LOGICAL                        :: SkipPointers_local
   ErrStat = ErrID_None
   ErrMsg  = ""
   
   IF (PRESENT(SkipPointers)) THEN
      SkipPointers_local = SkipPointers
   ELSE
      SkipPointers_local = .false.
   END IF
   
   ! -- ptfmLd Output Data fields
   IF ( .NOT. SkipPointers_local ) THEN
      IF ( .NOT. C_ASSOCIATED( OutputData%C_obj%ptfmLd ) ) THEN
         NULLIFY( OutputData%ptfmLd )
      ELSE
         CALL C_F_POINTER(OutputData%C_obj%ptfmLd, OutputData%ptfmLd, [OutputData%C_obj%ptfmLd_Len])
      END IF
   END IF
END SUBROUTINE

SUBROUTINE ExtPtfmLdDX_F2C_CopyOutput( OutputData, ErrStat, ErrMsg, SkipPointers  )
   TYPE(ExtPtfmLdDX_OutputType), INTENT(INOUT) :: OutputData
   INTEGER(IntKi),  INTENT(  OUT) :: ErrStat
   CHARACTER(*),    INTENT(  OUT) :: ErrMsg
   LOGICAL,OPTIONAL,INTENT(IN   ) :: SkipPointers
   ! 
   LOGICAL                        :: SkipPointers_local
   ErrStat = ErrID_None
   ErrMsg  = ''
   
   IF (PRESENT(SkipPointers)) THEN
      SkipPointers_local = SkipPointers
   ELSE
      SkipPointers_local = .false.
   END IF
   
   ! -- ptfmLd Output Data fields
   IF (.NOT. SkipPointers_local ) THEN
      IF (.NOT. ASSOCIATED(OutputData%ptfmLd)) THEN 
         OutputData%C_obj%ptfmLd_Len = 0
         OutputData%C_obj%ptfmLd = C_NULL_PTR
      ELSE
         OutputData%C_obj%ptfmLd_Len = SIZE(OutputData%ptfmLd)
         IF (OutputData%C_obj%ptfmLd_Len > 0) &
            OutputData%C_obj%ptfmLd = C_LOC(OutputData%ptfmLd(lbound(OutputData%ptfmLd,1)))
      END IF
   END IF
END SUBROUTINE

subroutine ExtPtfmLdDX_Input_ExtrapInterp(u, t, u_out, t_out, ErrStat, ErrMsg)
   !
   ! This subroutine calculates a extrapolated (or interpolated) Input u_out at time t_out, from previous/future time
   ! values of u (which has values associated with times in t).  Order of the interpolation is given by the size of u
   !
   !  expressions below based on either
   !
   !  f(t) = a
   !  f(t) = a + b * t, or
   !  f(t) = a + b * t + c * t**2
   !
   !  where a, b and c are determined as the solution to
   !  f(t1) = u1, f(t2) = u2, f(t3) = u3  (as appropriate)
   !
   !----------------------------------------------------------------------------------------------------------------------------------
   
   type(ExtPtfmLdDX_InputType), intent(in)  :: u(:) ! Input at t1 > t2 > t3
   real(DbKi),                 intent(in   )  :: t(:)           ! Times associated with the Inputs
   type(ExtPtfmLdDX_InputType), intent(inout)  :: u_out ! Input at tin_out
   real(DbKi),                 intent(in   )  :: t_out           ! time to be extrap/interp'd to
   integer(IntKi),             intent(  out)  :: ErrStat         ! Error status of the operation
   character(*),               intent(  out)  :: ErrMsg          ! Error message if ErrStat /= ErrID_None
   ! local variables
   integer(IntKi)                             :: order           ! order of polynomial fit (max 2)
   integer(IntKi)                             :: ErrStat2        ! local errors
   character(ErrMsgLen)                       :: ErrMsg2         ! local errors
   character(*),    PARAMETER                 :: RoutineName = 'ExtPtfmLdDX_Input_ExtrapInterp'
   
   ! Initialize ErrStat
   ErrStat = ErrID_None
   ErrMsg  = ''
   if (size(t) /= size(u)) then
      call SetErrStat(ErrID_Fatal, 'size(t) must equal size(u)', ErrStat, ErrMsg, RoutineName)
      return
   endif
   order = size(u) - 1
   select case (order)
   case (0)
      call ExtPtfmLdDX_CopyInput(u(1), u_out, MESH_UPDATECOPY, ErrStat2, ErrMsg2)
         call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   case (1)
      call ExtPtfmLdDX_Input_ExtrapInterp1(u(1), u(2), t, u_out, t_out, ErrStat2, ErrMsg2)
         call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   case (2)
      call ExtPtfmLdDX_Input_ExtrapInterp2(u(1), u(2), u(3), t, u_out, t_out, ErrStat2, ErrMsg2)
         call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   case default
      call SetErrStat(ErrID_Fatal, 'size(u) must be less than 4 (order must be less than 3).', ErrStat, ErrMsg, RoutineName)
      return
   end select
end subroutine

SUBROUTINE ExtPtfmLdDX_Input_ExtrapInterp1(u1, u2, tin, u_out, tin_out, ErrStat, ErrMsg )
!
! This subroutine calculates a extrapolated (or interpolated) Input u_out at time t_out, from previous/future time
! values of u (which has values associated with times in t).  Order of the interpolation is 1.
!
!  f(t) = a + b * t, or
!
!  where a and b are determined as the solution to
!  f(t1) = u1, f(t2) = u2
!
!..................................................................................................................................

   TYPE(ExtPtfmLdDX_InputType), INTENT(IN)  :: u1    ! Input at t1 > t2
   TYPE(ExtPtfmLdDX_InputType), INTENT(IN)  :: u2    ! Input at t2 
   REAL(DbKi),         INTENT(IN   )          :: tin(2)   ! Times associated with the Inputs
   TYPE(ExtPtfmLdDX_InputType), INTENT(INOUT)  :: u_out ! Input at tin_out
   REAL(DbKi),         INTENT(IN   )          :: tin_out  ! time to be extrap/interp'd to
   INTEGER(IntKi),     INTENT(  OUT)          :: ErrStat  ! Error status of the operation
   CHARACTER(*),       INTENT(  OUT)          :: ErrMsg   ! Error message if ErrStat /= ErrID_None
   ! local variables
   REAL(DbKi)                                 :: t(2)     ! Times associated with the Inputs
   REAL(DbKi)                                 :: t_out    ! Time to which to be extrap/interpd
   CHARACTER(*),                    PARAMETER :: RoutineName = 'ExtPtfmLdDX_Input_ExtrapInterp1'
   REAL(DbKi)                                 :: a1, a2   ! temporary for extrapolation/interpolation
   INTEGER(IntKi)                             :: ErrStat2 ! local errors
   CHARACTER(ErrMsgLen)                       :: ErrMsg2  ! local errors
   INTEGER                                    :: i01      ! dim1 level 0 counter variable for arrays of ddts
   INTEGER                                    :: i1       ! dim1 counter variable for arrays
   ! Initialize ErrStat
   ErrStat = ErrID_None
   ErrMsg  = ''
   ! we'll subtract a constant from the times to resolve some 
   ! numerical issues when t gets large (and to simplify the equations)
   t = tin - tin(1)
   t_out = tin_out - tin(1)
   
   IF (EqualRealNos(t(1), t(2))) THEN
      CALL SetErrStat(ErrID_Fatal, 't(1) must not equal t(2) to avoid a division-by-zero error.', ErrStat, ErrMsg, RoutineName)
      RETURN
   END IF
   
   ! Calculate weighting factors from Lagrange polynomial
   a1 = -(t_out - t(2))/t(2)
   a2 = t_out/t(2)
   
   IF (ASSOCIATED(u_out%ptfmDef) .AND. ASSOCIATED(u1%ptfmDef)) THEN
      u_out%ptfmDef = a1*u1%ptfmDef + a2*u2%ptfmDef
   END IF ! check if allocated
END SUBROUTINE

SUBROUTINE ExtPtfmLdDX_Input_ExtrapInterp2(u1, u2, u3, tin, u_out, tin_out, ErrStat, ErrMsg )
!
! This subroutine calculates a extrapolated (or interpolated) Input u_out at time t_out, from previous/future time
! values of u (which has values associated with times in t).  Order of the interpolation is 2.
!
!  expressions below based on either
!
!  f(t) = a + b * t + c * t**2
!
!  where a, b and c are determined as the solution to
!  f(t1) = u1, f(t2) = u2, f(t3) = u3
!
!..................................................................................................................................

   TYPE(ExtPtfmLdDX_InputType), INTENT(IN)  :: u1      ! Input at t1 > t2 > t3
   TYPE(ExtPtfmLdDX_InputType), INTENT(IN)  :: u2      ! Input at t2 > t3
   TYPE(ExtPtfmLdDX_InputType), INTENT(IN)  :: u3      ! Input at t3
   REAL(DbKi),                 INTENT(IN   )  :: tin(3)    ! Times associated with the Inputs
   TYPE(ExtPtfmLdDX_InputType), INTENT(INOUT)  :: u_out     ! Input at tin_out
   REAL(DbKi),                 INTENT(IN   )  :: tin_out   ! time to be extrap/interp'd to
   INTEGER(IntKi),             INTENT(  OUT)  :: ErrStat   ! Error status of the operation
   CHARACTER(*),               INTENT(  OUT)  :: ErrMsg    ! Error message if ErrStat /= ErrID_None
   ! local variables
   REAL(DbKi)                                 :: t(3)      ! Times associated with the Inputs
   REAL(DbKi)                                 :: t_out     ! Time to which to be extrap/interpd
   INTEGER(IntKi)                             :: order     ! order of polynomial fit (max 2)
   REAL(DbKi)                                 :: a1,a2,a3 ! temporary for extrapolation/interpolation
   INTEGER(IntKi)                             :: ErrStat2 ! local errors
   CHARACTER(ErrMsgLen)                       :: ErrMsg2  ! local errors
   CHARACTER(*),            PARAMETER         :: RoutineName = 'ExtPtfmLdDX_Input_ExtrapInterp2'
   INTEGER                                    :: i01    ! dim1 level 0 counter variable for arrays of ddts
   INTEGER                                    :: i1    ! dim1 counter variable for arrays
   ! Initialize ErrStat
   ErrStat = ErrID_None
   ErrMsg  = ''
   ! we'll subtract a constant from the times to resolve some 
   ! numerical issues when t gets large (and to simplify the equations)
   t = tin - tin(1)
   t_out = tin_out - tin(1)
   
   IF ( EqualRealNos( t(1), t(2) ) ) THEN
      CALL SetErrStat(ErrID_Fatal, 't(1) must not equal t(2) to avoid a division-by-zero error.', ErrStat, ErrMsg,RoutineName)
      RETURN
   ELSE IF ( EqualRealNos( t(2), t(3) ) ) THEN
      CALL SetErrStat(ErrID_Fatal, 't(2) must not equal t(3) to avoid a division-by-zero error.', ErrStat, ErrMsg,RoutineName)
      RETURN
   ELSE IF ( EqualRealNos( t(1), t(3) ) ) THEN
      CALL SetErrStat(ErrID_Fatal, 't(1) must not equal t(3) to avoid a division-by-zero error.', ErrStat, ErrMsg,RoutineName)
      RETURN
   END IF
   
   ! Calculate Lagrange polynomial coefficients
   a1 = (t_out - t(2))*(t_out - t(3))/((t(1) - t(2))*(t(1) - t(3)))
   a2 = (t_out - t(1))*(t_out - t(3))/((t(2) - t(1))*(t(2) - t(3)))
   a3 = (t_out - t(1))*(t_out - t(2))/((t(3) - t(1))*(t(3) - t(2)))
   IF (ASSOCIATED(u_out%ptfmDef) .AND. ASSOCIATED(u1%ptfmDef)) THEN
      u_out%ptfmDef = a1*u1%ptfmDef + a2*u2%ptfmDef + a3*u3%ptfmDef
   END IF ! check if allocated
END SUBROUTINE

subroutine ExtPtfmLdDX_Output_ExtrapInterp(y, t, y_out, t_out, ErrStat, ErrMsg)
   !
   ! This subroutine calculates a extrapolated (or interpolated) Output y_out at time t_out, from previous/future time
   ! values of y (which has values associated with times in t).  Order of the interpolation is given by the size of y
   !
   !  expressions below based on either
   !
   !  f(t) = a
   !  f(t) = a + b * t, or
   !  f(t) = a + b * t + c * t**2
   !
   !  where a, b and c are determined as the solution to
   !  f(t1) = y1, f(t2) = y2, f(t3) = y3  (as appropriate)
   !
   !----------------------------------------------------------------------------------------------------------------------------------
   
   type(ExtPtfmLdDX_OutputType), intent(in)  :: y(:) ! Output at t1 > t2 > t3
   real(DbKi),                 intent(in   )  :: t(:)           ! Times associated with the Outputs
   type(ExtPtfmLdDX_OutputType), intent(inout)  :: y_out ! Output at tin_out
   real(DbKi),                 intent(in   )  :: t_out           ! time to be extrap/interp'd to
   integer(IntKi),             intent(  out)  :: ErrStat         ! Error status of the operation
   character(*),               intent(  out)  :: ErrMsg          ! Error message if ErrStat /= ErrID_None
   ! local variables
   integer(IntKi)                             :: order           ! order of polynomial fit (max 2)
   integer(IntKi)                             :: ErrStat2        ! local errors
   character(ErrMsgLen)                       :: ErrMsg2         ! local errors
   character(*),    PARAMETER                 :: RoutineName = 'ExtPtfmLdDX_Output_ExtrapInterp'
   
   ! Initialize ErrStat
   ErrStat = ErrID_None
   ErrMsg  = ''
   if (size(t) /= size(y)) then
      call SetErrStat(ErrID_Fatal, 'size(t) must equal size(y)', ErrStat, ErrMsg, RoutineName)
      return
   endif
   order = size(y) - 1
   select case (order)
   case (0)
      call ExtPtfmLdDX_CopyOutput(y(1), y_out, MESH_UPDATECOPY, ErrStat2, ErrMsg2)
         call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   case (1)
      call ExtPtfmLdDX_Output_ExtrapInterp1(y(1), y(2), t, y_out, t_out, ErrStat2, ErrMsg2)
         call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   case (2)
      call ExtPtfmLdDX_Output_ExtrapInterp2(y(1), y(2), y(3), t, y_out, t_out, ErrStat2, ErrMsg2)
         call SetErrStat(ErrStat2, ErrMsg2, ErrStat, ErrMsg, RoutineName)
   case default
      call SetErrStat(ErrID_Fatal, 'size(y) must be less than 4 (order must be less than 3).', ErrStat, ErrMsg, RoutineName)
      return
   end select
end subroutine

SUBROUTINE ExtPtfmLdDX_Output_ExtrapInterp1(y1, y2, tin, y_out, tin_out, ErrStat, ErrMsg )
!
! This subroutine calculates a extrapolated (or interpolated) Output y_out at time t_out, from previous/future time
! values of y (which has values associated with times in t).  Order of the interpolation is 1.
!
!  f(t) = a + b * t, or
!
!  where a and b are determined as the solution to
!  f(t1) = y1, f(t2) = y2
!
!..................................................................................................................................

   TYPE(ExtPtfmLdDX_OutputType), INTENT(IN)  :: y1    ! Output at t1 > t2
   TYPE(ExtPtfmLdDX_OutputType), INTENT(IN)  :: y2    ! Output at t2 
   REAL(DbKi),         INTENT(IN   )          :: tin(2)   ! Times associated with the Outputs
   TYPE(ExtPtfmLdDX_OutputType), INTENT(INOUT)  :: y_out ! Output at tin_out
   REAL(DbKi),         INTENT(IN   )          :: tin_out  ! time to be extrap/interp'd to
   INTEGER(IntKi),     INTENT(  OUT)          :: ErrStat  ! Error status of the operation
   CHARACTER(*),       INTENT(  OUT)          :: ErrMsg   ! Error message if ErrStat /= ErrID_None
   ! local variables
   REAL(DbKi)                                 :: t(2)     ! Times associated with the Outputs
   REAL(DbKi)                                 :: t_out    ! Time to which to be extrap/interpd
   CHARACTER(*),                    PARAMETER :: RoutineName = 'ExtPtfmLdDX_Output_ExtrapInterp1'
   REAL(DbKi)                                 :: a1, a2   ! temporary for extrapolation/interpolation
   INTEGER(IntKi)                             :: ErrStat2 ! local errors
   CHARACTER(ErrMsgLen)                       :: ErrMsg2  ! local errors
   INTEGER                                    :: i01      ! dim1 level 0 counter variable for arrays of ddts
   INTEGER                                    :: i1       ! dim1 counter variable for arrays
   ! Initialize ErrStat
   ErrStat = ErrID_None
   ErrMsg  = ''
   ! we'll subtract a constant from the times to resolve some 
   ! numerical issues when t gets large (and to simplify the equations)
   t = tin - tin(1)
   t_out = tin_out - tin(1)
   
   IF (EqualRealNos(t(1), t(2))) THEN
      CALL SetErrStat(ErrID_Fatal, 't(1) must not equal t(2) to avoid a division-by-zero error.', ErrStat, ErrMsg, RoutineName)
      RETURN
   END IF
   
   ! Calculate weighting factors from Lagrange polynomial
   a1 = -(t_out - t(2))/t(2)
   a2 = t_out/t(2)
   
   IF (ASSOCIATED(y_out%ptfmLd) .AND. ASSOCIATED(y1%ptfmLd)) THEN
      y_out%ptfmLd = a1*y1%ptfmLd + a2*y2%ptfmLd
   END IF ! check if allocated
END SUBROUTINE

SUBROUTINE ExtPtfmLdDX_Output_ExtrapInterp2(y1, y2, y3, tin, y_out, tin_out, ErrStat, ErrMsg )
!
! This subroutine calculates a extrapolated (or interpolated) Output y_out at time t_out, from previous/future time
! values of y (which has values associated with times in t).  Order of the interpolation is 2.
!
!  expressions below based on either
!
!  f(t) = a + b * t + c * t**2
!
!  where a, b and c are determined as the solution to
!  f(t1) = y1, f(t2) = y2, f(t3) = y3
!
!..................................................................................................................................

   TYPE(ExtPtfmLdDX_OutputType), INTENT(IN)  :: y1      ! Output at t1 > t2 > t3
   TYPE(ExtPtfmLdDX_OutputType), INTENT(IN)  :: y2      ! Output at t2 > t3
   TYPE(ExtPtfmLdDX_OutputType), INTENT(IN)  :: y3      ! Output at t3
   REAL(DbKi),                 INTENT(IN   )  :: tin(3)    ! Times associated with the Outputs
   TYPE(ExtPtfmLdDX_OutputType), INTENT(INOUT)  :: y_out     ! Output at tin_out
   REAL(DbKi),                 INTENT(IN   )  :: tin_out   ! time to be extrap/interp'd to
   INTEGER(IntKi),             INTENT(  OUT)  :: ErrStat   ! Error status of the operation
   CHARACTER(*),               INTENT(  OUT)  :: ErrMsg    ! Error message if ErrStat /= ErrID_None
   ! local variables
   REAL(DbKi)                                 :: t(3)      ! Times associated with the Outputs
   REAL(DbKi)                                 :: t_out     ! Time to which to be extrap/interpd
   INTEGER(IntKi)                             :: order     ! order of polynomial fit (max 2)
   REAL(DbKi)                                 :: a1,a2,a3 ! temporary for extrapolation/interpolation
   INTEGER(IntKi)                             :: ErrStat2 ! local errors
   CHARACTER(ErrMsgLen)                       :: ErrMsg2  ! local errors
   CHARACTER(*),            PARAMETER         :: RoutineName = 'ExtPtfmLdDX_Output_ExtrapInterp2'
   INTEGER                                    :: i01    ! dim1 level 0 counter variable for arrays of ddts
   INTEGER                                    :: i1    ! dim1 counter variable for arrays
   ! Initialize ErrStat
   ErrStat = ErrID_None
   ErrMsg  = ''
   ! we'll subtract a constant from the times to resolve some 
   ! numerical issues when t gets large (and to simplify the equations)
   t = tin - tin(1)
   t_out = tin_out - tin(1)
   
   IF ( EqualRealNos( t(1), t(2) ) ) THEN
      CALL SetErrStat(ErrID_Fatal, 't(1) must not equal t(2) to avoid a division-by-zero error.', ErrStat, ErrMsg,RoutineName)
      RETURN
   ELSE IF ( EqualRealNos( t(2), t(3) ) ) THEN
      CALL SetErrStat(ErrID_Fatal, 't(2) must not equal t(3) to avoid a division-by-zero error.', ErrStat, ErrMsg,RoutineName)
      RETURN
   ELSE IF ( EqualRealNos( t(1), t(3) ) ) THEN
      CALL SetErrStat(ErrID_Fatal, 't(1) must not equal t(3) to avoid a division-by-zero error.', ErrStat, ErrMsg,RoutineName)
      RETURN
   END IF
   
   ! Calculate Lagrange polynomial coefficients
   a1 = (t_out - t(2))*(t_out - t(3))/((t(1) - t(2))*(t(1) - t(3)))
   a2 = (t_out - t(1))*(t_out - t(3))/((t(2) - t(1))*(t(2) - t(3)))
   a3 = (t_out - t(1))*(t_out - t(2))/((t(3) - t(1))*(t(3) - t(2)))
   IF (ASSOCIATED(y_out%ptfmLd) .AND. ASSOCIATED(y1%ptfmLd)) THEN
      y_out%ptfmLd = a1*y1%ptfmLd + a2*y2%ptfmLd + a3*y3%ptfmLd
   END IF ! check if allocated
END SUBROUTINE
END MODULE ExtPtfmLoadsDX_Types
!ENDOFREGISTRYGENERATEDFILE
